
# Service
---
apiVersion: v1
kind: Service
metadata:
  name: redis-incr
  labels:
    app: redis-incr
spec:
  ports:
    - name: client
      port: 6379
      targetPort: 6379
  clusterIP: None
  selector:
    app: redis-incr


# StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-incr
spec:
  serviceName: redis-incr
  replicas: 3
  selector:
    matchLabels:
      app: redis-incr
  template:
    metadata:
      labels:
        app: redis-incr
    spec:
      containers:
        - name: redis-incr
          image: redis:latest
          command: ["redis-server"]
          args:
            - "--cluster-enabled"
            - "yes"
            - "--cluster-node-timeout"
            - "5000"
            - "--appendonly"
            - "yes"
            - "--cluster-config-file"
            - "/data/nodes.conf"
          env:
            - name: REDIS_CLUSTER_ANNOUNCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: redis-incr-data
              mountPath: /data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: redis-incr-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  

# Jobs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redisincr-cluster-init
spec:
  template:
    spec:
      containers:
        - name: redisincr-cluster-init
          image: redis:latest
          command:
            - bash
            - -c
            - |
                echo "Aguardando Redis..."

                for i in 0 1 2; do
                  until redis-cli -h redis-incr-$i.redis-incr.default.svc.cluster.local ping | grep PONG; do
                    echo "Esperando redis-incr-$i..."
                    sleep 2
                  done
                done

                echo "Obtendo IPs dos pods Redis..."
                until IP0=$(getent hosts redis-incr-0.redis-incr.default.svc.cluster.local | awk '{ print $1 }'); do sleep 2; done
                until IP1=$(getent hosts redis-incr-1.redis-incr.default.svc.cluster.local | awk '{ print $1 }'); do sleep 2; done
                until IP2=$(getent hosts redis-incr-2.redis-incr.default.svc.cluster.local | awk '{ print $1 }'); do sleep 2; done

                echo "IPs detectados:"
                echo "$IP0"
                echo "$IP1"
                echo "$IP2"

                echo "Formando cluster com IPs reais..."
                yes yes | redis-cli --cluster create \
                  $IP0:6379 \
                  $IP1:6379 \
                  $IP2:6379 \
                  --cluster-replicas 0

                echo "Verificando estado do cluster..."
                until redis-cli -h $IP0 -p 6379 cluster info | grep -q cluster_state:ok; do
                  echo "Cluster ainda não está OK, aguardando..."
                  sleep 2
                done

                echo "Cluster formado e verificado com sucesso."
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: redisincr-init
spec:
  template:
    spec:
      containers:
        - name: redisincr-init
          image: bitnami/redis:latest
          command:
            - bash
            - -c
            - |
                REDIS_HOST="redis-incr.default.svc.cluster.local"
                REDIS_PORT=6379

                echo "Aguardando DNS resolver..."
                until getent hosts "$REDIS_HOST"; do
                  echo "Aguardando DNS resolver $REDIS_HOST..."
                  sleep 2
                done

                echo "Aguardando Redis responder..."
                until redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" ping | grep -q PONG; do
                  sleep 2
                done

                echo "Aguardando cluster estar OK..."
                until redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" cluster info | grep -q cluster_state:ok; do
                  sleep 2
                done

                echo "Verificando se contador já existe..."
                EXISTE=$(redis-cli -h redis-incr-0.redis-incr.default.svc.cluster.local EXISTS url_counter | grep -E '^[0-9]+$')

                if [ "${EXISTE:-0}" -eq 0 ]; then
                  echo "Definindo contador inicial..."
                  redis-cli -c -h redis-incr-0.redis-incr.default.svc.cluster.local SET url_counter 14000000
                  echo "Contador inicializado com sucesso"
                else
                  echo "Contador já existe, não será redefinido"
                fi

      restartPolicy: Never